# Generated by Django 6.0.2 on 2026-04-01 06:20

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long.'), common.validators.InputFieldValidator(message='Username contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[common.validators.InputFieldValidator(message='First name contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[common.validators.InputFieldValidator(message='Last name contains invalid characters.')]),
        ),
    ]
