# Generated by Django 6.0.2 on 2026-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_username_alter_profile_first_name_and_more'),
        ('products', '0022_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to='products.product'),
        ),
    ]
