# Generated by Django 6.0.2 on 2026-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphones', 'Headphones'), ('speakers', 'Speaker'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
