# Generated by Django 6.0.2 on 2026-03-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_title_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless', models.BooleanField(default=False)),
                ('noise_cancelling', models.BooleanField(default=False)),
                ('battery_life', models.CharField(blank=True, max_length=50)),
                ('microphone', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headphones', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_type', models.CharField(max_length=50)),
                ('keyboard_layout', models.CharField(max_length=50)),
                ('rgb_lighting', models.BooleanField(default=False)),
                ('wireless', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=50)),
                ('programmable_buttons', models.PositiveIntegerField()),
                ('wireless', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_output', models.CharField(max_length=50)),
                ('bluetooth', models.BooleanField(default=False)),
                ('portable', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='products.product')),
            ],
        ),
    ]
