# Generated by Django 6.0.2 on 2026-03-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_computer_headphones_keyboard_mouse_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='screen_size',
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to='products.product')),
            ],
        ),
    ]
