# Generated by Django 6.0.2 on 2026-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='programmable_buttons',
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.PositiveIntegerField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')], default=4),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='dpi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='power_output',
            field=models.PositiveIntegerField(),
        ),
    ]
