# Generated by Django 6.0.2 on 2026-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_laptop_ram_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.CharField(choices=[(128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB'), (2048, '2 TB'), (4096, '4 TB')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(choices=[(13, '13 inch'), (14, '14 inch'), (15, '15.6 inch'), (16, '16 inch'), (17, '17.3 inch')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(choices=[(128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB'), (2048, '2 TB'), (4096, '4 TB')]),
        ),
    ]
