# Generated by Django 6.0.2 on 2026-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_laptop_ram_alter_laptop_screen_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.PositiveIntegerField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.PositiveIntegerField(choices=[(128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB'), (2048, '2 TB'), (4096, '4 TB')]),
        ),
    ]
