# Generated by Django 6.0.2 on 2026-03-12 08:45

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_computer_ram_alter_computer_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, validators=[products.validators.InputFieldValidator(message='GPU contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(max_length=100, validators=[products.validators.InputFieldValidator(message='Processor contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, validators=[products.validators.InputFieldValidator(message='GPU contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=100, validators=[products.validators.InputFieldValidator(message='Processor contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=3000, validators=[products.validators.InputFieldValidator(message='Product description contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[products.validators.InputFieldValidator(message='Product name contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=4, validators=[products.validators.DigitFieldValidator()]),
        ),
    ]
