# Generated by Django 6.0.2 on 2026-03-12 08:51

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_computer_gpu_alter_computer_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphones',
            name='battery_life',
            field=models.CharField(blank=True, max_length=50, validators=[common.validators.DigitFieldValidator()]),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='keyboard_layout',
            field=models.CharField(max_length=50, validators=[
                common.validators.InputFieldValidator(message='Keyboard layout contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='switch_type',
            field=models.CharField(max_length=50, validators=[
                common.validators.InputFieldValidator(message='Switch type contains invalid characters.')]),
        ),
    ]
