# Generated by Django 6.0.2 on 2026-03-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_headphones_battery_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphones', 'Headphones'), ('speakers', 'Speaker'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
