# Generated by Django 6.0.2 on 2026-03-12 11:10

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(max_length=100, validators=[products.validators.InputFieldValidator(message='GPU contains invalid characters.')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(max_length=100, validators=[products.validators.InputFieldValidator(message='GPU contains invalid characters.')]),
        ),
    ]
