# Generated by Django 6.0.2 on 2026-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.PositiveIntegerField(choices=[(128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1, '1 TB'), (2, '2 TB'), (3, '4 TB')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.PositiveIntegerField(choices=[(128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1, '1 TB'), (2, '2 TB'), (3, '4 TB')]),
        ),
    ]
