# Generated by Django 6.0.2 on 2026-03-29 10:52

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_computer_storage_alter_laptop_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[products.validators.DigitFieldValidator()]),
        ),
    ]
