# Generated by Django 6.0.2 on 2026-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphones', 'Headphones'), ('speakers', 'Speaker')], max_length=20),
        ),
    ]
